name: Diversity Woman
pygments: false
markdown: kramdown
paginate: 10
version: 0.9
seo:
  author: "Diversity Women's Business Leadership Conference"
  description: "Diversity Women's Business Leadership Conference has proven to be a groundbreaking platform for a diverse set of women from all walks of life."
  tags: 'leadership conferences for women, black women in business, business leadership conference, women business conference, women and leadership conference, women in leadership development conference, advancing women in leadership conference 2015, women in leadership conference 2015'

contact:
  phone: ''
  email: ''
  address: ''

url: 'http://conference2015.diversitywoman.com/'
permalink: /:title

social:


google:
  analytics : 'UA-43775034-1'
  domain: 'diversitywoman.com'

facebook:
  admins : ''
  api : ''

assets:
  img: '/assets/images/'
  css: '/assets/stylesheets/'
  js: '/assets/javascripts/'
  speaker: '/assets/images/speakers/'
  sponsor: '/assets/images/sponsors/'
  honoree: '/assets/images/honorees/'

eventbrite:
  event-id: '7020860583'
  app-key: '4HSDJIEFIFGXFYAM2Z'
